---
# vars file for roles/apache_0.0.1
    liste_pkg:
      - git
      - vim
      - apache2=2.4.38-3+deb10u4
      - aptitude
    appli_enable: present
    mon_appli_port: 80
    mon_appli: formation