---
- name: PLAY - Demo facts
  hosts: linux
  
  tasks:
  
    # Utilisation de facts recoltes par la task automatique gathering_facts
    - name: Utilisation d'un facts
      debug:
      #msg: "Serveur sur distri: {{ ansible_distribution }}"
        msg: "Serveur sur distri: {{ ansible_facts.distribution }}"
     
    # Recuperer la memoire free des noeuds et afficher un message quand elle est inférieur à une valeur
    # appel d'un fact et une conditionnals
    - name: "Recuperation de la memoire free et message si <1000"
      debug:
        msg: "Oups: ce serveur est un peu light en memoire free : {{ ansible_facts.memfree_mb }}"
      when: ansible_facts.memfree_mb <1000